name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Buildozer Action
        uses: ArtemSerebriakov/buildozer-action@v1
        with:
          buildozer_version: master
          python_version: 3.8
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: Whitemask-APK
          path: bin/*.apk
